# CMake generated Testfile for 
# Source directory: C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger/test
# Build directory: C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(DocTestsTest_ledger-mode "C:/Python27/python.exe" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger/test/DocTests.py" "--ledger" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/Debug/ledger.exe" "--file" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger/doc/ledger-mode.texi")
  set_tests_properties(DocTestsTest_ledger-mode PROPERTIES  ENVIRONMENT "TZ=America/Chicago")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(DocTestsTest_ledger-mode "C:/Python27/python.exe" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger/test/DocTests.py" "--ledger" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/Release/ledger.exe" "--file" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger/doc/ledger-mode.texi")
  set_tests_properties(DocTestsTest_ledger-mode PROPERTIES  ENVIRONMENT "TZ=America/Chicago")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(DocTestsTest_ledger-mode "C:/Python27/python.exe" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger/test/DocTests.py" "--ledger" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/MinSizeRel/ledger.exe" "--file" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger/doc/ledger-mode.texi")
  set_tests_properties(DocTestsTest_ledger-mode PROPERTIES  ENVIRONMENT "TZ=America/Chicago")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(DocTestsTest_ledger-mode "C:/Python27/python.exe" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger/test/DocTests.py" "--ledger" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/RelWithDebInfo/ledger.exe" "--file" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger/doc/ledger-mode.texi")
  set_tests_properties(DocTestsTest_ledger-mode PROPERTIES  ENVIRONMENT "TZ=America/Chicago")
else()
  add_test(DocTestsTest_ledger-mode NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(DocTestsTest_ledger3 "C:/Python27/python.exe" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger/test/DocTests.py" "--ledger" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/Debug/ledger.exe" "--file" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger/doc/ledger3.texi")
  set_tests_properties(DocTestsTest_ledger3 PROPERTIES  ENVIRONMENT "TZ=America/Chicago")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(DocTestsTest_ledger3 "C:/Python27/python.exe" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger/test/DocTests.py" "--ledger" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/Release/ledger.exe" "--file" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger/doc/ledger3.texi")
  set_tests_properties(DocTestsTest_ledger3 PROPERTIES  ENVIRONMENT "TZ=America/Chicago")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(DocTestsTest_ledger3 "C:/Python27/python.exe" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger/test/DocTests.py" "--ledger" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/MinSizeRel/ledger.exe" "--file" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger/doc/ledger3.texi")
  set_tests_properties(DocTestsTest_ledger3 PROPERTIES  ENVIRONMENT "TZ=America/Chicago")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(DocTestsTest_ledger3 "C:/Python27/python.exe" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger/test/DocTests.py" "--ledger" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/RelWithDebInfo/ledger.exe" "--file" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger/doc/ledger3.texi")
  set_tests_properties(DocTestsTest_ledger3 PROPERTIES  ENVIRONMENT "TZ=America/Chicago")
else()
  add_test(DocTestsTest_ledger3 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(CheckBaselineTests "C:/Python27/python.exe" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger/test/CheckBaselineTests.py" "--ledger" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/Debug/ledger.exe" "--source" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger")
  set_tests_properties(CheckBaselineTests PROPERTIES  ENVIRONMENT "TZ=America/Chicago")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(CheckBaselineTests "C:/Python27/python.exe" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger/test/CheckBaselineTests.py" "--ledger" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/Release/ledger.exe" "--source" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger")
  set_tests_properties(CheckBaselineTests PROPERTIES  ENVIRONMENT "TZ=America/Chicago")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(CheckBaselineTests "C:/Python27/python.exe" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger/test/CheckBaselineTests.py" "--ledger" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/MinSizeRel/ledger.exe" "--source" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger")
  set_tests_properties(CheckBaselineTests PROPERTIES  ENVIRONMENT "TZ=America/Chicago")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(CheckBaselineTests "C:/Python27/python.exe" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger/test/CheckBaselineTests.py" "--ledger" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/RelWithDebInfo/ledger.exe" "--source" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger")
  set_tests_properties(CheckBaselineTests PROPERTIES  ENVIRONMENT "TZ=America/Chicago")
else()
  add_test(CheckBaselineTests NOT_AVAILABLE)
endif()
subdirs(unit)
subdirs(manual)
subdirs(baseline)
subdirs(regress)
