# CMake generated Testfile for 
# Source directory: C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger/test/manual
# Build directory: C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/test/manual
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(ManualTest_transaction-codes-1 "C:/Python27/python.exe" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger/test/RegressTests.py" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/Debug/ledger.exe" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger/test/manual/transaction-codes-1.test")
  set_tests_properties(ManualTest_transaction-codes-1 PROPERTIES  ENVIRONMENT "TZ=America/Chicago")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(ManualTest_transaction-codes-1 "C:/Python27/python.exe" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger/test/RegressTests.py" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/Release/ledger.exe" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger/test/manual/transaction-codes-1.test")
  set_tests_properties(ManualTest_transaction-codes-1 PROPERTIES  ENVIRONMENT "TZ=America/Chicago")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(ManualTest_transaction-codes-1 "C:/Python27/python.exe" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger/test/RegressTests.py" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/MinSizeRel/ledger.exe" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger/test/manual/transaction-codes-1.test")
  set_tests_properties(ManualTest_transaction-codes-1 PROPERTIES  ENVIRONMENT "TZ=America/Chicago")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(ManualTest_transaction-codes-1 "C:/Python27/python.exe" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger/test/RegressTests.py" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/RelWithDebInfo/ledger.exe" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger/test/manual/transaction-codes-1.test")
  set_tests_properties(ManualTest_transaction-codes-1 PROPERTIES  ENVIRONMENT "TZ=America/Chicago")
else()
  add_test(ManualTest_transaction-codes-1 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(ManualTest_transaction-codes-2 "C:/Python27/python.exe" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger/test/RegressTests.py" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/Debug/ledger.exe" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger/test/manual/transaction-codes-2.test")
  set_tests_properties(ManualTest_transaction-codes-2 PROPERTIES  ENVIRONMENT "TZ=America/Chicago")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(ManualTest_transaction-codes-2 "C:/Python27/python.exe" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger/test/RegressTests.py" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/Release/ledger.exe" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger/test/manual/transaction-codes-2.test")
  set_tests_properties(ManualTest_transaction-codes-2 PROPERTIES  ENVIRONMENT "TZ=America/Chicago")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(ManualTest_transaction-codes-2 "C:/Python27/python.exe" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger/test/RegressTests.py" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/MinSizeRel/ledger.exe" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger/test/manual/transaction-codes-2.test")
  set_tests_properties(ManualTest_transaction-codes-2 PROPERTIES  ENVIRONMENT "TZ=America/Chicago")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(ManualTest_transaction-codes-2 "C:/Python27/python.exe" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger/test/RegressTests.py" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/RelWithDebInfo/ledger.exe" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger/test/manual/transaction-codes-2.test")
  set_tests_properties(ManualTest_transaction-codes-2 PROPERTIES  ENVIRONMENT "TZ=America/Chicago")
else()
  add_test(ManualTest_transaction-codes-2 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(ManualTest_transaction-notes-1 "C:/Python27/python.exe" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger/test/RegressTests.py" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/Debug/ledger.exe" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger/test/manual/transaction-notes-1.test")
  set_tests_properties(ManualTest_transaction-notes-1 PROPERTIES  ENVIRONMENT "TZ=America/Chicago")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(ManualTest_transaction-notes-1 "C:/Python27/python.exe" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger/test/RegressTests.py" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/Release/ledger.exe" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger/test/manual/transaction-notes-1.test")
  set_tests_properties(ManualTest_transaction-notes-1 PROPERTIES  ENVIRONMENT "TZ=America/Chicago")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(ManualTest_transaction-notes-1 "C:/Python27/python.exe" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger/test/RegressTests.py" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/MinSizeRel/ledger.exe" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger/test/manual/transaction-notes-1.test")
  set_tests_properties(ManualTest_transaction-notes-1 PROPERTIES  ENVIRONMENT "TZ=America/Chicago")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(ManualTest_transaction-notes-1 "C:/Python27/python.exe" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger/test/RegressTests.py" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/RelWithDebInfo/ledger.exe" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger/test/manual/transaction-notes-1.test")
  set_tests_properties(ManualTest_transaction-notes-1 PROPERTIES  ENVIRONMENT "TZ=America/Chicago")
else()
  add_test(ManualTest_transaction-notes-1 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(ManualTest_transaction-notes-2 "C:/Python27/python.exe" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger/test/RegressTests.py" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/Debug/ledger.exe" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger/test/manual/transaction-notes-2.test")
  set_tests_properties(ManualTest_transaction-notes-2 PROPERTIES  ENVIRONMENT "TZ=America/Chicago")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(ManualTest_transaction-notes-2 "C:/Python27/python.exe" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger/test/RegressTests.py" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/Release/ledger.exe" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger/test/manual/transaction-notes-2.test")
  set_tests_properties(ManualTest_transaction-notes-2 PROPERTIES  ENVIRONMENT "TZ=America/Chicago")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(ManualTest_transaction-notes-2 "C:/Python27/python.exe" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger/test/RegressTests.py" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/MinSizeRel/ledger.exe" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger/test/manual/transaction-notes-2.test")
  set_tests_properties(ManualTest_transaction-notes-2 PROPERTIES  ENVIRONMENT "TZ=America/Chicago")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(ManualTest_transaction-notes-2 "C:/Python27/python.exe" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger/test/RegressTests.py" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/RelWithDebInfo/ledger.exe" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger/test/manual/transaction-notes-2.test")
  set_tests_properties(ManualTest_transaction-notes-2 PROPERTIES  ENVIRONMENT "TZ=America/Chicago")
else()
  add_test(ManualTest_transaction-notes-2 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(ManualTest_transaction-notes-3 "C:/Python27/python.exe" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger/test/RegressTests.py" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/Debug/ledger.exe" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger/test/manual/transaction-notes-3.test")
  set_tests_properties(ManualTest_transaction-notes-3 PROPERTIES  ENVIRONMENT "TZ=America/Chicago")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(ManualTest_transaction-notes-3 "C:/Python27/python.exe" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger/test/RegressTests.py" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/Release/ledger.exe" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger/test/manual/transaction-notes-3.test")
  set_tests_properties(ManualTest_transaction-notes-3 PROPERTIES  ENVIRONMENT "TZ=America/Chicago")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(ManualTest_transaction-notes-3 "C:/Python27/python.exe" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger/test/RegressTests.py" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/MinSizeRel/ledger.exe" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger/test/manual/transaction-notes-3.test")
  set_tests_properties(ManualTest_transaction-notes-3 PROPERTIES  ENVIRONMENT "TZ=America/Chicago")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(ManualTest_transaction-notes-3 "C:/Python27/python.exe" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger/test/RegressTests.py" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/RelWithDebInfo/ledger.exe" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger/test/manual/transaction-notes-3.test")
  set_tests_properties(ManualTest_transaction-notes-3 PROPERTIES  ENVIRONMENT "TZ=America/Chicago")
else()
  add_test(ManualTest_transaction-notes-3 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(ManualTest_transaction-notes-4 "C:/Python27/python.exe" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger/test/RegressTests.py" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/Debug/ledger.exe" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger/test/manual/transaction-notes-4.test")
  set_tests_properties(ManualTest_transaction-notes-4 PROPERTIES  ENVIRONMENT "TZ=America/Chicago")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(ManualTest_transaction-notes-4 "C:/Python27/python.exe" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger/test/RegressTests.py" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/Release/ledger.exe" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger/test/manual/transaction-notes-4.test")
  set_tests_properties(ManualTest_transaction-notes-4 PROPERTIES  ENVIRONMENT "TZ=America/Chicago")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(ManualTest_transaction-notes-4 "C:/Python27/python.exe" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger/test/RegressTests.py" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/MinSizeRel/ledger.exe" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger/test/manual/transaction-notes-4.test")
  set_tests_properties(ManualTest_transaction-notes-4 PROPERTIES  ENVIRONMENT "TZ=America/Chicago")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(ManualTest_transaction-notes-4 "C:/Python27/python.exe" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger/test/RegressTests.py" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/RelWithDebInfo/ledger.exe" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger/test/manual/transaction-notes-4.test")
  set_tests_properties(ManualTest_transaction-notes-4 PROPERTIES  ENVIRONMENT "TZ=America/Chicago")
else()
  add_test(ManualTest_transaction-notes-4 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(ManualTest_transaction-status-1 "C:/Python27/python.exe" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger/test/RegressTests.py" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/Debug/ledger.exe" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger/test/manual/transaction-status-1.test")
  set_tests_properties(ManualTest_transaction-status-1 PROPERTIES  ENVIRONMENT "TZ=America/Chicago")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(ManualTest_transaction-status-1 "C:/Python27/python.exe" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger/test/RegressTests.py" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/Release/ledger.exe" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger/test/manual/transaction-status-1.test")
  set_tests_properties(ManualTest_transaction-status-1 PROPERTIES  ENVIRONMENT "TZ=America/Chicago")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(ManualTest_transaction-status-1 "C:/Python27/python.exe" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger/test/RegressTests.py" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/MinSizeRel/ledger.exe" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger/test/manual/transaction-status-1.test")
  set_tests_properties(ManualTest_transaction-status-1 PROPERTIES  ENVIRONMENT "TZ=America/Chicago")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(ManualTest_transaction-status-1 "C:/Python27/python.exe" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger/test/RegressTests.py" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/RelWithDebInfo/ledger.exe" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger/test/manual/transaction-status-1.test")
  set_tests_properties(ManualTest_transaction-status-1 PROPERTIES  ENVIRONMENT "TZ=America/Chicago")
else()
  add_test(ManualTest_transaction-status-1 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(ManualTest_transaction-status-2 "C:/Python27/python.exe" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger/test/RegressTests.py" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/Debug/ledger.exe" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger/test/manual/transaction-status-2.test")
  set_tests_properties(ManualTest_transaction-status-2 PROPERTIES  ENVIRONMENT "TZ=America/Chicago")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(ManualTest_transaction-status-2 "C:/Python27/python.exe" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger/test/RegressTests.py" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/Release/ledger.exe" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger/test/manual/transaction-status-2.test")
  set_tests_properties(ManualTest_transaction-status-2 PROPERTIES  ENVIRONMENT "TZ=America/Chicago")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(ManualTest_transaction-status-2 "C:/Python27/python.exe" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger/test/RegressTests.py" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/MinSizeRel/ledger.exe" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger/test/manual/transaction-status-2.test")
  set_tests_properties(ManualTest_transaction-status-2 PROPERTIES  ENVIRONMENT "TZ=America/Chicago")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(ManualTest_transaction-status-2 "C:/Python27/python.exe" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger/test/RegressTests.py" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/RelWithDebInfo/ledger.exe" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger/test/manual/transaction-status-2.test")
  set_tests_properties(ManualTest_transaction-status-2 PROPERTIES  ENVIRONMENT "TZ=America/Chicago")
else()
  add_test(ManualTest_transaction-status-2 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(ManualTest_transaction-status-3 "C:/Python27/python.exe" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger/test/RegressTests.py" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/Debug/ledger.exe" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger/test/manual/transaction-status-3.test")
  set_tests_properties(ManualTest_transaction-status-3 PROPERTIES  ENVIRONMENT "TZ=America/Chicago")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(ManualTest_transaction-status-3 "C:/Python27/python.exe" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger/test/RegressTests.py" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/Release/ledger.exe" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger/test/manual/transaction-status-3.test")
  set_tests_properties(ManualTest_transaction-status-3 PROPERTIES  ENVIRONMENT "TZ=America/Chicago")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(ManualTest_transaction-status-3 "C:/Python27/python.exe" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger/test/RegressTests.py" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/MinSizeRel/ledger.exe" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger/test/manual/transaction-status-3.test")
  set_tests_properties(ManualTest_transaction-status-3 PROPERTIES  ENVIRONMENT "TZ=America/Chicago")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(ManualTest_transaction-status-3 "C:/Python27/python.exe" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger/test/RegressTests.py" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/RelWithDebInfo/ledger.exe" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger/test/manual/transaction-status-3.test")
  set_tests_properties(ManualTest_transaction-status-3 PROPERTIES  ENVIRONMENT "TZ=America/Chicago")
else()
  add_test(ManualTest_transaction-status-3 NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(ManualTest_transaction-status-4 "C:/Python27/python.exe" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger/test/RegressTests.py" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/Debug/ledger.exe" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger/test/manual/transaction-status-4.test")
  set_tests_properties(ManualTest_transaction-status-4 PROPERTIES  ENVIRONMENT "TZ=America/Chicago")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(ManualTest_transaction-status-4 "C:/Python27/python.exe" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger/test/RegressTests.py" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/Release/ledger.exe" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger/test/manual/transaction-status-4.test")
  set_tests_properties(ManualTest_transaction-status-4 PROPERTIES  ENVIRONMENT "TZ=America/Chicago")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(ManualTest_transaction-status-4 "C:/Python27/python.exe" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger/test/RegressTests.py" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/MinSizeRel/ledger.exe" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger/test/manual/transaction-status-4.test")
  set_tests_properties(ManualTest_transaction-status-4 PROPERTIES  ENVIRONMENT "TZ=America/Chicago")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(ManualTest_transaction-status-4 "C:/Python27/python.exe" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger/test/RegressTests.py" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/RelWithDebInfo/ledger.exe" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger" "C:/Users/charlie/Documents/Visual Studio 2015/Projects/ledger-windows/ledger/test/manual/transaction-status-4.test")
  set_tests_properties(ManualTest_transaction-status-4 PROPERTIES  ENVIRONMENT "TZ=America/Chicago")
else()
  add_test(ManualTest_transaction-status-4 NOT_AVAILABLE)
endif()
